name: Update README Directory

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tree
        run: sudo apt-get install -y tree  

      - name: Generate Directory Structure
        run: |
          tree -I "node_modules|.git|.github" > structure.txt
          export LC_ALL=C.UTF-8
          sed -i '/<!-- START_DIR_STRUCTURE -->/,/<!-- END_DIR_STRUCTURE -->/d' README.md
          sed -i '/<!-- START_DIR_STRUCTURE -->/a \
          '"$(cat structure.txt)"'
          ' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update directory structure in README.md" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
