name: Update README Directory

on:
  push:
    branches:
      - main  # Active only when pushing to main
  schedule:
    - cron: "0 0 * * 1"  # Automatically runs on Mondays

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pull the code

      - name: Install tree
        run: sudo apt-get install tree  

      - name: Generate Directory Structure
        run: |
          tree -I "node_modules|.git|.github" > structure.txt
          export LC_ALL=C.UTF-8  # Ensure consistent encoding
          printf '<!-- START_DIR_STRUCTURE -->\n%s\n<!-- END_DIR_STRUCTURE -->\n' "$(cat structure.txt)" > tmp.txt
          sed -i '/<!-- START_DIR_STRUCTURE -->/,/<!-- END_DIR_STRUCTURE -->/c\'"$(cat tmp.txt)" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update directory structure in README.md" || echo "No changes to commit"
          git push
